-- Add individual test types to the report_type enum
ALTER TYPE public.report_type ADD VALUE IF NOT EXISTS 'cbc';
ALTER TYPE public.report_type ADD VALUE IF NOT EXISTS 'lft';
ALTER TYPE public.report_type ADD VALUE IF NOT EXISTS 'rft';
ALTER TYPE public.report_type ADD VALUE IF NOT EXISTS 'lipid_profile';
ALTER TYPE public.report_type ADD VALUE IF NOT EXISTS 'esr';
ALTER TYPE public.report_type ADD VALUE IF NOT EXISTS 'bsr';
ALTER TYPE public.report_type ADD VALUE IF NOT EXISTS 'bsf';
ALTER TYPE public.report_type ADD VALUE IF NOT EXISTS 'serum_calcium';
ALTER TYPE public.report_type ADD VALUE IF NOT EXISTS 'mp';
ALTER TYPE public.report_type ADD VALUE IF NOT EXISTS 'typhoid';
ALTER TYPE public.report_type ADD VALUE IF NOT EXISTS 'hcv';
ALTER TYPE public.report_type ADD VALUE IF NOT EXISTS 'hbsag';
ALTER TYPE public.report_type ADD VALUE IF NOT EXISTS 'hiv';
ALTER TYPE public.report_type ADD VALUE IF NOT EXISTS 'vdrl';
ALTER TYPE public.report_type ADD VALUE IF NOT EXISTS 'h_pylori';
ALTER TYPE public.report_type ADD VALUE IF NOT EXISTS 'blood_group';
ALTER TYPE public.report_type ADD VALUE IF NOT EXISTS 'ra_factor';